# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Setup Accumulo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke-accumulo:
    runs-on: ubuntu-latest
    steps:
    - name: Allow password-less ssh to localhost
      run: |
        if [ ! -f "$HOME/.ssh/id_rsa.pub" ]; then
          ssh-keygen -q -t rsa -N '' -f ~/.ssh/id_rsa
        fi
        cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Checkout fluo-uno
      uses: actions/checkout@v3
      with:
        repository: bxkftechteam/fluo-uno
        ref: accumulo_2.1.0
        path: ./fluo-uno
    - run: ./fluo-uno/bin/uno fetch accumulo
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - run: ./fluo-uno/bin/uno setup accumulo
