name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true
      draft:
        description: 'Draft'
        required: true
        type: boolean
        default: false
      overwrite:
        description: 'Overwrite existing release'
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and publish jar
        run: |
          mvn --batch-mode deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Build 2
        run: |
          mkdir -p test-dir
          echo "hello-1" > test-dir/hello-1.txt
          echo "hello-2" > test-dir/hello-2.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.version }}
          draft: ${{ github.event.inputs.draft }}
          make_latest: ${{ ! github.event.inputs.draft }}
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            target/*.jar
            Release.txt
            test-dir/*
            LICENSE
